### ISSUE TITLE
Common usecase, who use this?

### ISSUE THREAD

**Issue by nguyentruongtho** [gotify/server#165]
It seems helpful, but I wonder who use it in production and what are the most common benefit it brings to people other than just having fun?

**Comment by GalvinGao** [comment]
Self-hosted services enable you to take full control of your service, and at the same time letting your messages stay in your local network instead of flying across the internet. Use in production is also possible due to the limitation of Google's Firebase Notification Service in China where software developers *have* to host their notification platforms. At such usage, Gotify usually becomes handy.

**Comment by eternal-flame-AD** [comment]
Sorry but I am having difficulty understanding your question.

If you are asking for what people are using this project for, why not join the community chat and ask other users for their experience? Or you can simply ask "I am not sure if this project is stable enough and is there anyone using this project in production environments?".

Please remember that this is a free FOSS project, no one is benefiting from or taking responsibility for any usability, warranty or liability on the project. As you come across this project on GitHub, it is completely up to you to grab the project and deploy it anywhere you want, no matter production servers that makes your company thousands of dollars everyday or a micro computer in your home lab just for fun, if you don't find it useful it also does not cost you a cent to flip through to another project.

So, please clearify your question, or I think this issue can only be closed because it is not constructive.

**Comment by nguyentruongtho** [comment]
The question is mainly for understanding the intention of building this. I totally see how interesting it is, but I'm trying to understand the motivation behind it :). I don't doubt anything about the project, I should have checked out the chat but it wasn't very visible to me.

Thanks and please feel free to close.

**Comment by eternal-flame-AD** [comment]
Okay then, I think @GalvinGao has answered your question.

Next time please try to make your issue description clearer and ask what information do you want in a direct way.

**Comment by nguyentruongtho** [comment]
I think it was pretty clear and directly asked, otherwise @GalvinGao couldn't answered so good.

**Comment by cosminadrianpopescu** [comment]
I came across this question by mistake, actually searching for another question, but I can also answer it, even though a little late. 

I am using it on my own server. Since I've developed my imap client as an ionic application I have issues in android doing polling from the phone. 

So, I deployed gotify on my own server to do the poling of the imap server and then to push the notifications on my phone. 

So, my ionic app can be killed by the OS (android). I will still receive messages like you would receive them in your android imap client. 

Why am I doing this? Very easy. I have a de-googled phone and I don't use Firebase or any other proprietary owned service to push notifications. What would be the point to go through all the trouble of not using a gmail account, not using google play services, not using any google products if after all this I pass all my messages to google for push notifications? :)
