### ISSUE TITLE
Tables failed to initialize on MariaDB

### ISSUE THREAD

**Issue by rerobins** [gotify/server#174]
Initial installation and configuration directions do not show that specific mysql configuration values need to be set for the following issue:

(Error 1709: Index column size too large. The maximum column size is 767 bytes.) 
[2019-03-15 19:09:51] 

More details about how to fix the issue are in https://stackoverflow.com/questions/24853828/index-column-size-too-large-the-maximum-column-size-is-767-bytes-for-int-dat

**Comment by atajsic** [comment]
Good Afternoon,

I was also also having this issue. 
`Ubuntu 18.04`
`Gotify version 2.0.4`
`MariaDB 10.1.38-MariaDB-0ubuntu0.18.04.1`

This is the default, and the current on Ubuntu's 18.04 repo.

I added MariaDB's repo, and upgraded MariaDB to 10.3.14, which solved the issue.
Considering it is the default of an LTS build, I thought I'd mention it here.

Kindest Regards,
Andrew

**Comment by eternal-flame-AD** [comment]
@atajsic
Thanks for the research:) I will try to reproduce this and see if we can do anything to resolve this these days.

**Comment by eternal-flame-AD** [comment]
I think this is caused by [this](https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_large_prefix) change in the default value to `innodb_large_prefix`. We could have two ways to resolve this:
- Document this problem and require MariaDB users using `<=MariaDB 10.2.1` to explicitly set this config option before initializing the database.
- Limit all indexed fields within 767 bytes.

I think the second option is better.

/cc @jmattheis

**Comment by jmattheis** [comment]
Limiting the indexed fields to x bytes seems like the right approach, good catch!
