### ISSUE TITLE
Run gotify in docker as non-root user

### ISSUE THREAD

**Issue by bn4t** [gotify/server#187]
It would be awesome if gotify would be run as a non-root user in docker.

**Comment by eternal-flame-AD** [comment]
Is there any benefit for this? According my experiences I have not come up with any service that runs as a custom user in docker.

**Comment by bn4t** [comment]
In case of a container breakout the process wouldn't run as root on the host.
I'm aware that a container breakout is unlikely but it would still be nice to not run gotify as root in the container.

**Comment by eternal-flame-AD** [comment]
The container has another user system isolated from the host system, so I don't think the user in the container affects its power on the host.

**Comment by bn4t** [comment]
User namespaces are available since Docker 1.10. However by default users are not namespaced.

From the docs ([link](https://docs.docker.com/engine/security/security/#other-kernel-security-features)):

> As of Docker 1.10 User Namespaces are supported directly by the docker daemon. This feature allows for the root user in a container to be mapped to a non uid-0 user outside the container, which can help to mitigate the risks of container breakout. This facility is available but not enabled by default.

It is possible to manually map the user root to a different user on the host, although I don't think many people actually do this.

I think that changing the user under which gotify runs would increase the security of most deployments.

**Comment by eternal-flame-AD** [comment]
I am aware of this, and I agree with you that this actually increases security, but this is more of a docker daemon configuration problem rather than a problem to be mitigated on the container side. When a user want to use this feature, he only needs to set his `dockerd` to run under another user, and there won't be a difference in the procedures to deploy the gotify container on the docker daemon.

**Comment by ppacher** [comment]
Unfortunately it is not as simple as letting dockerd run as a different user because docker needs root access to setup all the namespaces required for container isolation. One possibility, as pointed out by @bn4t , is to enable user-namespaces. However, this is a bit complicated and may break existing/running containers. Moreover, not using root is actually recommended by docker [1] and many services avoid using it. Changing the user will only cause problems if gotify is instructed to listen on a privileged port (<1024). However, since we can use the port-mapping feature of docker this should not be a problem (`-p 443:8443` if gotify listens on 8443 instead of 443).

[1] https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
