### ISSUE TITLE
Mark messages as read

### ISSUE THREAD

**Issue by jmattheis** [gotify/server#21]
* `Read bool` to `model.Message` 
* `POST /message/read` Body: `[]uint`
* `POST /message/unread` Body: `[]uint`

**Comment by jmattheis** [comment]
Closing this for now, because it is not really needed.

**Comment by ChathuraJW** [comment]
Hi, 
I believe mark as read or unread option is nice to have feature. With that users can flag as marked the notification without deleting from the system. It will improve the integration with third party app as well. Where user will mark as read though API, and it will not be available from the view, but later user can see what are the notifications since we are not deleting them from the system.
Thank you.
