### ISSUE TITLE
how I can get the application-token from a user without Web-UI

### ISSUE THREAD

**Issue by reschresch** [gotify/server#240]
Hello,
in my Application I want to send a message to one user. At this time I only know the username.
Actually I use in my source-code the application-token hardcodes - I see it in the Web-UI. 
But normally I dont know the token (for example it is a new username).

How I can get the application-token?  

Best regards,
reschresch

**Comment by reschresch** [comment]
I mean the client-token I want to get!

**Comment by ppacher** [comment]
Hey,

I guess you'r confusing application and client tokens. A client can query messages from the server and typically presents them to the user (like the Android client). An application can send notifications to a user (and thus all clients of that user). Both, the client and the application need an authentication token to prove they are allowed to query or publish respectively. 

Since you want to send a message to a specific user you need an application token. The short answer to your question unfortunately is that you cannot get that token via the API (unless you have the username AND Password and can create a new token).
The typical workflow is that a user wants an application to send notifications and therefore creates a new application token before and then tells the application about it.

If you checkout the gotify/cli repository you'll notice that you either need to configure an already existing token or enter your username+password so the cli can create a new one.

Hope that helps.

**Comment by reschresch** [comment]
Hello,
you are right with my confusion. I edit my question and the headline.
Thank you.

I understand that there is (actually) no possibility to get the application-token via the API. 
But how should it work? I can't believe that a "recipient-user" give another "sender-user" such a cryptic thing like a generated token.
I hoped that I can get the token with the credential of an user who have admin-rights and the "recipient-username". Or I can create a Application-token with admin-user for the "recipient-user".
Or misunderstood something in the conception?

Best regards,
reschresch

**Comment by jmattheis** [comment]
> get the application-token via the API.

https://gotify.net/api-docs#/application/createApp is the api for creating applications, however, because applications are bound to users, you need to have user credentials of the "recipient-user" to create one.

> I hoped that I can get the token with the credential of an user who have admin-rights and the "recipient-username". Or I can create a Application-token with admin-user for the "recipient-user".
Or misunderstood something in the conception?

This is not possible with the standard gotify, but you could add a plugin (https://gotify.net/docs/plugin) which could send message to specific users.

**Comment by reschresch** [comment]
Hello,
thank you very much.
You wrote "could add a plugin". Where I can find such a plugin? 
Or are you meaning I have to write one myself?

Best regards,
reschresch

**Comment by jmattheis** [comment]
Yeah, you'd have to write one yourself. Or find an existing one which solves your problem.
