### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by duylong** [gotify/server#259]
**Is your feature request related to a problem? Please describe.**

When I send a image with a high resolution (1980*1024 for example) to Gotify server, the image is very large in the display.

**Describe the solution you'd like**

Apply a default size (585px for example) in the display or show the image as an attachment.

**Comment by georgesuba** [comment]
- i do not understand you - you asking gotify server to do your job? if you uploading huge img to server its your space so you should take care of it.. use jpg or png optim or gimp or if you on windows use photoshop. 

I do not think so that should be included in gotify - as it will add palavas to install other things.. just do not be lazy and do your bit as you would anywhere on server. perhaps limit this feature to 1mb or much less by gotify would do the job in future...

**Comment by duylong** [comment]
It's always a tricky question, when I ask the developer the question, I'm told it's Gotify to do the verification, and here I'm told it's not a Gotify issue. It's like javascript, does the server always have to trust the client?
In the end, it is only a question of display so as not to go outside the edges (width css?), there is no need for processing on the image. You can also not display the image and put an option to attach as an attachment, here too there is no processing on the image.

**Comment by xiaolei0125** [comment]
I have same display issue in gotify web,  the image is 1920x1080 and it not display well in gotify web,  and android is normal.

Is any status update of this issue?

**Comment by jmattheis** [comment]
Nope, but feel free to create a pull request for this issue.

**Comment by MrLemur** [comment]
Hello, I have implemented a fix for this here: https://github.com/MrLemur/server/blob/148c71fca5caedb9c499f08f6cfee7b80e4dc010/ui/src/message/Message.tsx#L63

Would you be happy to accept a PR for this? Just adds `max-width: 100%` to any image in the message to stop it going out of bounds of the parent container.
