### ISSUE TITLE
Topic needed like FCM

### ISSUE THREAD

**Issue by happymario** [gotify/server#285]
**Is your feature request related to a problem? Please describe.**
I want to send messages by broadcast as fcm topics.

**Describe the solution you'd like**
Please add subscribe and unsubscribe topics like fcm.

**Describe alternatives you've considered**
I don't know alternatives solution.

**Comment by jmattheis** [comment]
Why do you want such a feature, could you add some use-cases?

**Comment by happymario** [comment]
As you can see, it is one feature of FCM.
It is very useful to send notification without token.

**Comment by jmattheis** [comment]
I like to keep gotify simple and this would require a major rewrite on serverside to function properly. Because of this I'll close this issue, as it is most likely not needed by most of the users of gotify.

Still, a feature like this could be implemented via our plugin api, you can find the documentation here  https://gotify.net/docs/plugin

**Comment by happymario** [comment]
simple? I understand.
Thank you for your support
