### ISSUE TITLE
Make default priority configurable

### ISSUE THREAD

**Issue by bhopmann** [gotify/server#312]
**Is your feature request related to a problem? Please describe.**
No, it isn't.

**Describe the solution you'd like**
It would be helpful, if the default `priority` (currently set to 0) would be configurable via config file and environment variables.

**Describe alternatives you've considered**
I haven't considered alternatives.

**Additional context**
There's no additional context.

**Comment by jmattheis** [comment]
I try to keep the settings of Gotify to a minimum. I think it doesn't hurt to always set the priority when sending a message. Let's wait for more feedback to decide if this feature should be implemented.

**Comment by Leosirth** [comment]
I think this would be useful.

I have a scenario where I'm sending notification from Grafana to Gotify.
Grafana doesn't allow to change the payload or to add parameters so the default priority is used (0) and the message is delivered silently to the clients.

I think having the possibility to set a default priority would help on this situation.

In my opinion this will be even better if it could be configured at application level instead of globally.
So we can have a default priority set differently for each application (if provided, otherwise 0 would be used).

**Comment by mdino-gh** [comment]
Hi, 
I try to use Gotify notification from my synology disk station. I managed it to configure it under SMS service provider. But if I am configuring the priority in the disk station configuration it is being sent as "priority":"5". Gotify denies the request because the priority value is quoted and therefore it seems that it's interpreted as a string instead of an integer.

{"error":"Bad Request","errorCode":400,"errorDescription":"json: cannot unmarshal string into Go struct field MessageExternal.priority of type int"}

I am not sure about JSON specification and I couldn't find a clear statement that quoting of integers is wrong.

Anyways if it would be possible e.g. to define a default priority for each application that would do a great job.

**Comment by hadogenes** [comment]
I think it would be best if you could configure default priority per app (in _Applications_ page)

**Comment by rightsaidfred99** [comment]
I wish

**Comment by jmattheis** [comment]
https://github.com/gotify/server/releases/tag/v2.3.0
