### ISSUE TITLE
Paginate Message APIs

### ISSUE THREAD

**Issue by jmattheis** [gotify/server#34]
Adjust APIs:
* `GET /application/{id}/message`
* `GET /message`

New Query Parameter:
* `limit=uint` the amount of messages to return
* ~`since=date` return all messages before this date (limited by limit)~
* `since=id` return all messages before the given message id

Expected Response:
``` json
{
    "paging": {
       "limit": 50,
       "next": "https://requesturl.com/message?limit=from-request&since=message-id"
    },
    "data": [
          {"id":12183,"appid":1,"message":"mymsg","title":"mytitle","priority":0,"date":"2018-03-20T19:30:51.596354+01:00"}
    ]
}
```

**Comment by lslah** [comment]
`since=id` is probably better as two messages might have the same date, see https://coderwall.com/p/lkcaag/pagination-you-re-probably-doing-it-wrong

**Comment by jmattheis** [comment]
@lslah Using ids for pagination seems to be better. Good point!

**Comment by naimo** [comment]
The name of the parameter seems weird to me : message ids get incremented, so the message received by the server "since" a given id are those with higher numbers.

Keeping the current behavior, the parameter should be renamed "until" or "before". Better though would be to keep "since" but actually return new messages. Seems to be a more frequent use case no ?

**Comment by jmattheis** [comment]
@naimo Naming is hard (:.

I think, I called it this way because the messages are sorted in descending order. Thus, `since` kinda makes sense. The behavior is also [documented](https://gotify.net/api-docs#/message/getMessages)
```
Ascending:
Message 1 |- until 3
Message 2 |
Message 3
Message 4 | 
Message 5 |- since 3

Descending:
Message 5 |- until 3
Message 4 |
Message 3
Message 2 | 
Message 1 |- since 3
```
I don't think this renaming would justify a breaking API change. 

> Better though would be to keep "since" but actually return new messages. Seems to be a more frequent use case no ?

It is actually not because new messages will be transmitted via web socket. Still, the API addition would have some use cases.

**Comment by naimo** [comment]
I see.

In my case I have a client (small esp8366-based display) which polls for
new messages on regular basis, not via websocket. It has limited memory so
only keeps track of the id of the last message it saw.
Being able to get only the messages "since" that last id would be
convenient instead of working it's way back until it reaches that id.

Thanks for the reply, and the great app.

**Comment by jmattheis** [comment]
@naimo  Yeah, our android app does something similar. I've created https://github.com/gotify/server/issues/329 to add this functionality.
