### ISSUE TITLE
Ubuntu 18.04 Start Error - GLIBC_2.28' not found

### ISSUE THREAD

**Issue by mskian** [gotify/server#361]
Latest Version `2.0.18` have a build error
like I faced in the version `2.0.7`

Here is My Pervious report #225

**Comment by jmattheis** [comment]
Yeah, the stretch version of the official Go docker image was removed probably because it doesn't receive security updates anymore. Thus, it now uses buster which uses glibc version 2.28. Ubuntu 18.04 currently has version 2.27. I'm opposed to creating our own golang build image but if version 2.27 must be supported there is no way around it. Have you considered upgrading to ubuntu 20.x?

**Comment by mskian** [comment]
Tested on ubuntu 20.x works well :100: 
but I need 18.x most of my scripts and apps are 18.x support only
so can't upgrade right now

**Comment by mskian** [comment]
Migrate My Gotify APP to my another server contain 20.x and work well
still, I need18.x support

**Comment by jmattheis** [comment]
Yeah, I'll create custom build images with a lower glibc version.

**Comment by jmattheis** [comment]
@mskian could you try out the newest version?

**Comment by mskian** [comment]
Perfect working now
