### ISSUE TITLE
Message queue by many users 

### ISSUE THREAD

**Issue by handfreezer** [gotify/server#491]
Hello, 

  The main idea is to be able to create a message queue owned by many users.  The goals is to be able to share the management of the tool.

  The extended feature of that is to be able to create groups of users, and roles like a owner, manager, operator, monitor. Then being able to assigned role to group or users.

Best regards

**Comment by jmattheis** [comment]
I agree, but this would require a major rework of everything inside gotify, because currently messages are bound to an application and applications are bound to a user. I have ideas how to implement this, but it just isn't worth the effort for me, because I don't need it.

Maybe https://github.com/eternal-flame-AD/gotify-broadcast fits your use case.
