### ISSUE TITLE
Force special character in token

### ISSUE THREAD

**Issue by LiloBzH** [gotify/server#681]
hello

would it be possible to force the presence of at least 1 special character in the token (like the - or the _).

The % or & are obviously to be banned for the uses of call via URL

Thanks

**Comment by eternal-flame-AD** [comment]
What exactly is your use case for this? I don't see how this improves security, it only reduces entropy of the generated token. 

Usually this is only needed when the result need to pass a "password strength" check out of your control, but I don't think tokens are intended to be passwords.

**Comment by LiloBzH** [comment]
only for security. I'm a bit paranoid about security.

With a special character, it's always better in my opinion than with none ^^

**Comment by eternal-flame-AD** [comment]
Unfortunately I don't feel like this justifies the additional logic needed to release this feature. However if you prefer this you could either make a fork or simply regenerate your client tokens until they have a symbol in them (I assume you don't need to do this a lot so a manual solution should suffice).

**Comment by LiloBzH** [comment]
for a token, it took about ten attempts anyway ^^

But no worries, I don't create new tokens every day.
Thanks for taking the time to answer and thanks for this application :)

**Comment by najtin** [comment]
> only for security. I'm a bit paranoid about security.
> 
> With a special character, it's always better in my opinion than with none ^^

Forcing a special character makes the key weaker and can thus not make this process more secure. Consider you buy ice cream. There are ten different ice creams to choose from. In this example you must choose two. You may also chose the same twice. This makes 50 different combinations you could choose (100 if order is important). Now i force you to choose strawberry ice cream at least once. Now there are only 10 different combinations (or 20 if order is important). You may see that it is far more likely to guess your combination by chance, since there are less combinations in the first place. 

In essence: If you care about security generate truly random tokens of sufficient length.

A word about passwords: The reason that people tell you to use special characters in passwords, is that people use the name of their cat as a password or somebodies birthday. This is bad and easy to guess. Adding some special characters makes the password slightly harder to guess. However, these days nobody should choose their password by hand or have to remember them all. Use a password manager like KeePassXC or even the built-in browser password manager. Let your password manager create your passwords and make them as long as possible.
