### ISSUE TITLE
A job for a plugin or something else?

### ISSUE THREAD

**Issue by BingEdison** [gotify/server#691]
Trying to prevent duplicate messages within the gotify database, messages with a duplicate title should be ignored, is it possible to do so with a gotify plugin? I see functionality for sending messages but not displaying them to user. Any insight would be much appreciated

**Comment by najtin** [comment]
Messages in gotify are notifications. So plugins can send messages/notifications to the user. Plugins can also store things, but they can't directly access the database i think. You can also create a webhook in the plugin. So you could write a plugin that receives the request and only sends creates a message if the title is unique. Then, send your request to the plugin instead of the default endpoint. Should be doable. I find this page https://gotify.net/docs/plugin-write and this repo https://github.com/gotify/plugin-template very helpful.

**Comment by najtin** [comment]
> I see functionality for sending messages but not displaying them to user. 

I'm sorry, maybe i don't understand correctly what you are searching for. Gotify has that build-in. This is basically the core functionality of gotify. Would you mind clarifying you question?

**Comment by eternal-flame-AD** [comment]
_maybe_ we can add a user custom message key/tag that is indexed by the DB, if the discussion ends with this is best fixed by the server itself. Title is designed to be human readable not to be matched by machines.

Want to clarify what is your use case? My guess is you have an app that tracks some external state list (like, newly added files, etc.) and you want to preserve the state when you restart? 

@najtin Thanks for the answer!

**Comment by BingEdison** [comment]
thanks for suggestions ,  modified message.go and use mapped titles to determine if new message is created
