### ISSUE TITLE
Ability to send notification using URL encoded string

### ISSUE THREAD

**Issue by GitStorageOne** [gotify/server#740]
**Is your feature request related to a problem? Please describe.**
Some third party software does not provide option to configure request BODY.  
I would like to bind a webhook event from UNIFI Protect 5 to Gotify.  
Unfortunately, only headers are configurable.  
So, Gotify returns HTTP 400.  

**Describe the solution you'd like**
Ability to specify message via URL parameters (with empty BODY) like so:  
`?msg="Some%20Url%20Encoded%20Message%2C%20like%20Doorbell%20RINGS%21"`  
(URL encoded string: `Some Url Encoded Message, like Doorbell RINGS!`)

**Describe alternatives you've considered**
I deployed Graylog and configured UNIFI console to send Syslogs.  
Unfortunately, Unifi Protect does not send events in a such way.

**Additional context**
For simple static messages, URL parameter would be handy option.

**Comment by eternal-flame-AD** [comment]
You can write `/message?token=xxx&message=test` as a query parameter in an empty POST but the declared content type cannot be JSON otherwise how to interpret the request is not clear.

We cannot accept messages submitted via GET because that is a separate endpoint and semantically not HTTP compliant.

The easiest way is to write a plugin or some kind of proxy to translate the request. Here's a [plugin](https://github.com/eternal-flame-AD/gotify-webhook-misskey) I wrote myself for a similar requirement of translating webhooks.

On the long run to fully fix this issue (which seems to happen a lot) maybe I can write a plugin that provides [gojq](https://github.com/itchyny/gojq) support on incoming messages to normalize it into gotify format?

**Comment by GitStorageOne** [comment]
> On the long run to fully fix this issue (which seems to happen a lot) maybe I can write a plugin that provides [gojq](https://github.com/itchyny/gojq) support on incoming messages to normalize it into gotify format?

I'm not familiar with gojq, but if it allows us to use a script to transform the request, I think that would be a great solution.
